check-l1-updated GHA

diff --git a/.github/workflows/code-health.yml b/.github/workflows/code-health.yml
--- a/.github/workflows/code-health.yml
+++ b/.github/workflows/code-health.yml
@@ -50,8 +50,29 @@ jobs:
       - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
       - name: Run ShellCheck
         uses: bewuethr/shellcheck-action@d01912909579c4b1a335828b8fca197fbb8e0aa4
+  check-l1-updated:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    steps:
+      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
+      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
+        with:
+          node-version: 18.x
+      - run: ./scripts/cdk-all.sh
+      - name: Find mutations
+        id: self_mutation
+        run: |-
+          git add .
+          git diff --staged --patch --exit-code > .repo.patch || echo "self_mutation_happened=true" >> "${GITHUB_OUTPUT}"
+      - name: Fail build on mutation
+        if: steps.self_mutation.outputs.self_mutation_happened
+        run: |-
+          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
+          cat .repo.patch
+          exit 1
   call-package-workflow:
-    needs: [compile, lint, shellcheck]
+    needs: [compile, lint, shellcheck, check-l1-updated]
     secrets: inherit
     permissions:
       contents: write
